/******************************************************************************
*                                                                        
*                   Copyright (c) by SoftDEL Systems Ltd.               
*                                                                        
*   This software is copyrighted by and is the sole property of SoftDEL
*   Systems Ltd. All rights, title, ownership, or other interests in the 
*   software remain the property of  SoftDEL Systems Ltd. This software 
*   may only be used in accordance with the corresponding license 
*   agreement. Any unauthorized use, duplication, transmission,
*   distribution, or disclosure of this software is expressly forbidden.  
*                                                                        
*   This Copyright notice may not be removed or modified without prior    
*   written consent of SoftDEL Systems Ltd.                                
*                                                                        
*   SoftDEL Systems Ltd. reserves the right to modify this software        
*   without notice.                                                       
*                                                                        
*   SoftDEL Systems Ltd.						india@softdel.com      
*   3rd Floor, Pentagon P4,						http://www.softdel.com
*   Magarpatta City, Hadapsar
*   Pune - 411 028       
*
*   File Name - apiServiceApi.c
*
*   AUTHORS
*	Kashinath G. Bhor
*
*   DESCRIPTION                                                            
*   Exported API's of SoftDEL's BACnet-IP Stack for A-side Services.
*
**************************************************************************/

/** header file includes */
#include "osalFreeRTOS.h"
#include "bacDELApi.h"
#include "bacnetInitiateServiceMgmt.h"
#include <string.h>


#ifdef BACDEL_SER_DM_DDB_A
/**
*
* DESCRIPTION
* API to send Who-Is service request.
*
* @param u32SrcDevId			 [in]  Source Device ID.
* @param u32DestDevId			 [in]  Destination Device ID.
* @param pstDestinationAdd		 [in]  Destination Device IP address.
* @param bDestTypeFlag			 [in]  Flag to check request generated by
*									   Device ID or Device address.
* @param eDestType				 [in]  Type of destination.
* @param bIsNwLayerMsg           [in]  Send either who_is or who_
*                                      is_router_to_network.
* @param u32NetworkNo            [in]  Network no for who_is_router_to_network.
* @param pstWhoIs                [in]  Structure pointer to access the data of
*                                      Who-Is service request
* @param u32RequestId	         [in]  Request ID generated by application.
*
* @param pi32TokenId			 [out] Token ID will be returned
* @return BACNET_RETURN_TYPE     [out] success or suitable error code.
*
*/
BACNET_RETURN_TYPE BACDEL_Send_Who_Is(
	uint32_t u32SrcDevId,
	uint32_t u32DestDevId,
	BACnetAddress_t *pstDestinationAdd,
	bool bDestTypeFlag,
	DESTINATION_TYPE eDestType,
	bool bIsNwLayerMsg,
	uint16_t u16NetworkNo,
	ddb_who_is_t *pstWhoIsData,
	int32_t *pi32TokenId,
	uint32_t u32RequestId)
{
    /* local variables */
    virtualDevData_t *pVirtualDev = NULL;
    BACNET_RETURN_TYPE eReturnVal = BACDEL_SUCCESS;
	bacnetip_arguments_t stServiceArgs;// = {0};
	initiator_response_t stInitRet;// = {0};
	BACnetAddress_t stDestAddr;// = {0};

	memset(&stDestAddr,0,sizeof(stDestAddr));
	memset(&stInitRet,0,sizeof(stInitRet));
	memset(&stServiceArgs,0,sizeof(stServiceArgs));
    /* api entry */
	#if(defined DEBUG_PRINTF && DL_3)
    Print_DebugMsg(DEBUG_LEVEL3, BACDEL_ENTRY_MESSAGE, "API: \
    BACDEL_Send_Who_Is: Entry \r\n");
	#endif

	/* check input pointers */
	if(NULL == pstWhoIsData || NULL == pi32TokenId)
	{
		#if(defined DEBUG_PRINTF && DL_0)
		Print_DebugMsg(DEBUG_LEVEL0, BACDEL_INVALID_INPUT_PARAMETER, "API: \
		BACDEL_Send_Who_Is: null input pointers \r\n");
		#endif
		return BACDEL_INVALID_INPUT_PARAMETER;
	}

    /* traverse the Host Device Link List */
    pVirtualDev = Find_In_Host_Device_List(u32SrcDevId);
    if(NULL == pVirtualDev)
    {
		/* host device not found */
		#if(defined DEBUG_PRINTF && DL_1)
		Print_DebugMsg(DEBUG_LEVEL1, BACDEL_DEVICE_NOT_PRESENT, "API: \
		BACDEL_Send_Who_Is: No Device \r\n");
		#endif
		return BACDEL_DEVICE_NOT_PRESENT;
    }

	/* Set default parameters */
	BACDEL_Set_Default_Parameters(&stServiceArgs, BACDEL_REQ_WHO_IS);

	/* Set destination address parameter as per destination type */
	eReturnVal = Copy_Destination_Parameter(eDestType,
		bDestTypeFlag,	u32DestDevId, pstDestinationAdd, &stDestAddr);

	if(BACDEL_SUCCESS != eReturnVal)
	{
		#if(defined DEBUG_PRINTF && DL_1)
		Print_DebugMsg(DEBUG_LEVEL1, eReturnVal, "API: \
		BACDEL_Send_Who_Is: Destination error \r\n");
		#endif
		return eReturnVal;
	}

	/* Set destination type */
    stServiceArgs.m_stNPDUData.m_eDestinationType = eDestType;
	/* save request-id value */
	stServiceArgs.m_u32RequestID = u32RequestId;

	/* Copy destination address */
	memcpy(&stServiceArgs.m_stDestBACnetAddr, &stDestAddr, sizeof(BACnetAddress_t));

	/* check destination type flag */
	if(true == bDestTypeFlag)
	{
		/* save device Id */
		stServiceArgs.m_u32DeviceID = u32DestDevId;
	}

	/* send Who-Is-Router-To-Network */
	if(TRUE == bIsNwLayerMsg)
	{
		stServiceArgs.m_stNPDUData.m_bIsNwLayerMsg = TRUE;
		stServiceArgs.m_stNPDUData.m_stAPDUData.m_stServiceChoice.
			m_u16RtrNetNumber = u16NetworkNo;
	}
	/* send Who-Is */
	else
	{
		/* Assign all parameters required to send WHO-IS */
		memcpy(&stServiceArgs.m_stNPDUData.m_stAPDUData.m_stServiceChoice.
			m_stWHO_IS_Request, pstWhoIsData, sizeof(ddb_who_is_t));
	}

	/* Generate the request */
	stInitRet = BACDEL_Generate_Aside_Request(pVirtualDev->m_u8DvSADR, &stServiceArgs, NULL);
	if(BACDEL_INITIATOR_SUCCESS != stInitRet.m_eRetType)
	{
		/* set the error code */
		eReturnVal = stInitRet.m_eErrorCode;
	}

	/* return token ID */
	*pi32TokenId = stInitRet.m_i32TokenID;

    /* api exit */
	#if(defined DEBUG_PRINTF && DL_3)
    Print_DebugMsg(DEBUG_LEVEL3, BACDEL_EXIT_MESSAGE, "API: \
    BACDEL_Send_Who_Is: Exit \r\n");
	#endif
    return eReturnVal;
}
#endif /* BACDEL_SER_DM_DDB_A */

#ifdef BACDEL_SER_DM_DDB_B
/**                                                                         
*
* DESCRIPTION                                                           
* API to send I-Am service request.
*
* @param u32SrcDevId			 [in]  Source Device ID. 
* @param u32DestDevId			 [in]  Destination Device ID. 
* @param pstDestinationAdd		 [in]  Destination Device IP address.
* @param bDestTypeFlag			 [in]  Flag to check request generated by
*									   Device ID or Device address. 
* @param eDestType				 [in]  Type of destination.
* @param bIsNwLayerMsg           [in]  Send either i_am or i_am_router_to_network.
* @param pstIAm        		     [in]  Structure pointer to access the data of 
*                                      I-Am service request
*
* @param pi32TokenId			 [out] Token ID will be returned
* @return BACNET_RETURN_TYPE     [out] success or suitable error code.
* 
*/
BACNET_RETURN_TYPE BACDEL_Send_I_Am(
	uint32_t u32SrcDevId,
	uint32_t u32DestDevId,
	BACnetAddress_t *pstDestinationAdd,
	bool bDestTypeFlag,
	DESTINATION_TYPE eDestType,
	bool bIsNwLayerMsg,
	int32_t *pi32TokenId)
{
    /* local variables */
    virtualDevData_t *pVirtualDev = NULL;
    BACNET_RETURN_TYPE eReturnVal = BACDEL_SUCCESS;
	bacnetip_arguments_t stServiceArgs;// = {0};
	initiator_response_t stInitRet;// = {0};
	//BACnetAddress_t stDestAddr = {0};
	//BACnetAddress_t stDestAddr = {0xff,0xff,0xff,0xff,0xff,0xff,0xff};
	BACnetAddress_t stDestAddr;// = {0xff};

	memset(&stDestAddr,0xff,sizeof(stDestAddr));
	memset(&stInitRet,0,sizeof(stInitRet));
	memset(&stServiceArgs,0,sizeof(stServiceArgs));
    /* api entry */
	#ifdef DEBUG_PRINTF
    Print_DebugMsg(DEBUG_LEVEL3,"BACnetStackAPI: \
    BACDEL_Send_I_Am: Entry \r\n");
	#endif

	/* check input pointers */
	if(NULL == pi32TokenId)
	{
		#ifdef DEBUG_PRINTF
		Print_DebugMsg(DEBUG_LEVEL0,"BACnetStackAPI: \
		BACDEL_Send_I_Am: null input pointers \r\n");
		#endif
		return BACDEL_INVALID_INPUT_PARAMETER;
	}

    /* traverse the Host Device Link List */
    pVirtualDev = Find_In_Host_Device_List(u32SrcDevId);
    if(NULL == pVirtualDev)
    {
		/* host device not found */
		#ifdef DEBUG_PRINTF
		Print_DebugMsg(DEBUG_LEVEL1,"BACnetStackAPI: \
		BACDEL_Send_I_Am: No Device \r\n");
		#endif
		return BACDEL_DEVICE_NOT_PRESENT;     
    }

    /*  Set default parameters */
	BACDEL_Set_Default_Parameters(&stServiceArgs, BACDEL_REQ_I_AM);

	/* Set destination address parameter as per destination type */
	eReturnVal = Copy_Destination_Parameter(eDestType, 
		bDestTypeFlag, u32DestDevId, pstDestinationAdd, &stDestAddr);
	
	if(BACDEL_SUCCESS != eReturnVal)
	{
		#ifdef DEBUG_PRINTF
		Print_DebugMsg(DEBUG_LEVEL1,"BACnetStackAPI: \
		BACDEL_Send_I_Am: Destination error \r\n");
		#endif
		return eReturnVal;     
	}

	/* Set destination type */
    stServiceArgs.m_stNPDUData.m_eDestinationType = eDestType;

	/* Copy destination address */
	memcpy(&stServiceArgs.m_stDestBACnetAddr, &stDestAddr, sizeof(BACnetAddress_t));

	/* check destination type flag */
	if(true == bDestTypeFlag)
	{
		/* save device Id */
		stServiceArgs.m_u32DeviceID = u32DestDevId;
	}

	/* Assign all parameters required to send I-AM */
    stServiceArgs.m_stNPDUData.m_stAPDUData.m_stServiceChoice.m_stI_AM_Request.
		m_u32DeviceInstance = pVirtualDev->m_stDevObject.m_stObjectID.m_u32ObjId;
    stServiceArgs.m_stNPDUData.m_stAPDUData.m_stServiceChoice.m_stI_AM_Request.m_u32VendorID 
		= pVirtualDev->m_stDevObject.m_stVendorId.m_u16Val;
    stServiceArgs.m_stNPDUData.m_stAPDUData.m_stServiceChoice.m_stI_AM_Request.
		m_u16MaxAPDUlengthAccepted = pVirtualDev->m_stDevObject.m_stMaxAPDULenAccepted.m_u16Val;
    stServiceArgs.m_stNPDUData.m_stAPDUData.m_stServiceChoice.m_stI_AM_Request.
		m_eSegmentationSupported = pVirtualDev->m_stDevObject.m_stSegmentationSupport.m_eSegmentationSupport;

    /* Generate the request */
	stInitRet = BACDEL_Generate_Aside_Request(pVirtualDev->m_u8DvSADR, &stServiceArgs, NULL);
	
	if(BACDEL_INITIATOR_SUCCESS != stInitRet.m_eRetType)
	{
		/* set the error code */
		eReturnVal = stInitRet.m_eErrorCode;
	}

	/* return token ID */
	*pi32TokenId = stInitRet.m_i32TokenID;

    /* api exit */
	#ifdef DEBUG_PRINTF
    Print_DebugMsg(DEBUG_LEVEL3,"BACnetStackAPI: \
    BACDEL_Send_I_Am: Exit \r\n");
	#endif
    return eReturnVal;
}
#endif /* BACDEL_SER_DM_DDB_B */

#ifdef BACDEL_SER_DM_DOB_B
/**
*
* DESCRIPTION
* API to send I-HAVE request.
*
* @param u32SrcDevId			 [in]  Source Device ID.
* @param u32DestDevId			 [in]  Destination Device ID.
* @param pstDestinationAdd		 [in]  Destination Device IP address.
* @param bDestTypeFlag			 [in]  Flag to check request generated by
*									   Device ID or Device address.
* @param eDestType				 [in]  Type of destination.
* @param pstIHaveData			 [in]  Structure pointer to access the data of
*                                      I HAVE service request
*
* @param pi32TokenId			 [out] Token ID will be returned
* @return BACNET_RETURN_TYPE     [out] success or suitable error code.
*
*/
 BACNET_RETURN_TYPE BACDEL_Send_I_Have(
	uint32_t u32SrcDevId,
	uint32_t u32DestDevId,
	BACnetAddress_t *pstDestinationAdd,
	bool bDestTypeFlag,
	DESTINATION_TYPE eDestType,
	dob_i_have_t *pstIHaveData,
	int32_t *pi32TokenId)
{
	/* local variables */
    virtualDevData_t *pVirtualDev = NULL;
    BACNET_RETURN_TYPE eReturnVal = BACDEL_SUCCESS;
	bacnetip_arguments_t stServiceArgs;// = {0};
	initiator_response_t stInitRet;// = {0};
	BACnetAddress_t stDestAddr;// = {0};

	memset(&stDestAddr,0,sizeof(stDestAddr));
	memset(&stInitRet,0,sizeof(stInitRet));
	memset(&stServiceArgs,0,sizeof(stServiceArgs));

    /* api entry */
	#ifdef DEBUG_PRINTF
    Print_DebugMsg(DEBUG_LEVEL3,"BACnetStackAPI: \
    BACDEL_Send_I_Have: Entry \r\n");
	#endif

	/* check input pointers */
	if(NULL == pstIHaveData || NULL == pi32TokenId)
	{
		#ifdef DEBUG_PRINTF
		Print_DebugMsg(DEBUG_LEVEL0,"BACnetStackAPI: \
		BACDEL_Send_I_Have: null input pointers \r\n");
		#endif
		return BACDEL_INVALID_INPUT_PARAMETER;
	}

    /* traverse the Host Device Link List */
    pVirtualDev = Find_In_Host_Device_List(u32SrcDevId);
    if(NULL == pVirtualDev)
    {
		/* host device not found */
		#ifdef DEBUG_PRINTF
		Print_DebugMsg(DEBUG_LEVEL1,"BACnetStackAPI: \
		BACDEL_Send_I_Have: No Device \r\n");
		#endif
		return BACDEL_DEVICE_NOT_PRESENT;
    }

    /*  Set default parameters */
	BACDEL_Set_Default_Parameters(&stServiceArgs, BACDEL_REQ_I_HAVE);

	/* Set destination address parameter as per destination type */
	eReturnVal = Copy_Destination_Parameter(eDestType,
		bDestTypeFlag, u32DestDevId, pstDestinationAdd, &stDestAddr);

	if(BACDEL_SUCCESS != eReturnVal)
	{
		#ifdef DEBUG_PRINTF
		Print_DebugMsg(DEBUG_LEVEL1,"BACnetStackAPI: \
		BACDEL_Send_I_Have: Destination error \r\n");
		#endif
		return eReturnVal;
	}

	/* Set destination type */
    stServiceArgs.m_stNPDUData.m_eDestinationType = eDestType;

	/* Copy destination address */
	memcpy(&stServiceArgs.m_stDestBACnetAddr, &stDestAddr, sizeof(BACnetAddress_t));

	/* check destination type flag */
	if(true == bDestTypeFlag)
	{
		/* save device Id */
		stServiceArgs.m_u32DeviceID = u32DestDevId;
	}

	/* Assign all parameters required to send I-HAVE */
	memcpy(&stServiceArgs.m_stNPDUData.m_stAPDUData.m_stServiceChoice.m_stI_HAVE_Request,
		pstIHaveData, sizeof(dob_i_have_t));

    /* Generate the request */
	stInitRet = BACDEL_Generate_Aside_Request(pVirtualDev->m_u8DvSADR, &stServiceArgs,
											 NULL);
	if(BACDEL_INITIATOR_SUCCESS != stInitRet.m_eRetType)
	{
		/* set the error code */
		eReturnVal = stInitRet.m_eErrorCode;
	}

	/* return token ID */
	*pi32TokenId = stInitRet.m_i32TokenID;

    /* api exit */
	#ifdef DEBUG_PRINTF
    Print_DebugMsg(DEBUG_LEVEL3,"BACnetStackAPI: \
    BACDEL_Send_I_Have: Exit \r\n");
	#endif
    return eReturnVal;
}

#endif /* BACDEL_SER_DM_DOB_B */

#ifdef BACDEL_PR23
#ifdef BACDEL_SER_DM_DDA_A
/**
*
* DESCRIPTION
* API to send You-Are-A service request.
*
* @param u32SrcDevId			 [in]  Source Device ID.
* @param u32DestDevId			 [in]  Destination Device ID.
* @param pstDestinationAdd		 [in]  Destination Device IP address.
* @param bDestTypeFlag			 [in]  Flag to check request generated by
*									   Device ID or Device address.
* @param eDestType				 [in]  Type of destination.
* @param pstYouAreData           [in]  Structure pointer to access the data of
*                                      You-Are service request
* @param u32RequestId	         [in]  Request ID generated by application.
*
* @param pi32TokenId			 [out] Token ID will be returned
* @return BACNET_RETURN_TYPE     [out] success or suitable error code.
*
*/
BACNET_STACK_EXPORT BACNET_RETURN_TYPE BACDEL_Send_You_Are(
	uint32_t u32SrcDevId,
	uint32_t u32DestDevId,
	BACnetAddress_t *pstDestinationAdd,
	bool bDestTypeFlag,
	DESTINATION_TYPE eDestType,
	dda_you_are_t *pstYouAreData,
	int32_t *pi32TokenId,
	uint32_t u32RequestId)
{
	/* local variables */
	virtualDevData_t *pVirtualDev = NULL;
	BACNET_RETURN_TYPE eReturnVal = BACDEL_SUCCESS;
	bacnetip_arguments_t stServiceArgs = { 0 };
	initiator_response_t stInitRet = { 0 };
	BACnetAddress_t stDestAddr = { 0 };

	/* api entry */
	#if(defined DEBUG_PRINTF && DL_3)
	Print_DebugMsg(DEBUG_LEVEL3, BACDEL_ENTRY_MESSAGE, "API: \
    BACDEL_Send_You_Are: Entry \r\n");
	#endif

	/* check input pointers */
	if(NULL == pstYouAreData || NULL == pi32TokenId)
	{
		#if(defined DEBUG_PRINTF && DL_0)
		Print_DebugMsg(DEBUG_LEVEL0, BACDEL_INVALID_INPUT_PARAMETER, "API: \
		BACDEL_Send_You_Are: null input pointers \r\n");
		#endif
		return BACDEL_INVALID_INPUT_PARAMETER;
	}

	/* traverse the Host Device Link List */
	pVirtualDev = Find_In_Host_Device_List(u32SrcDevId);
	/* validate the pointer */
	if(NULL == pVirtualDev)
	{
		/* host device not found */
		#if(defined DEBUG_PRINTF && DL_1)
		Print_DebugMsg(DEBUG_LEVEL1, BACDEL_DEVICE_NOT_PRESENT, "API: \
		BACDEL_Send_You_Are: No Device \r\n");
		#endif
		return BACDEL_DEVICE_NOT_PRESENT;
	}

	/*  Set default parameters */
	BACDEL_Set_Default_Parameters(&stServiceArgs, BACDEL_REQ_YOU_ARE);

	/* Set destination address parameter as per destination type */
	eReturnVal = Copy_Destination_Parameter(eDestType,
		bDestTypeFlag, u32DestDevId, pstDestinationAdd, &stDestAddr);
	/* validate the return value */
	if(BACDEL_SUCCESS != eReturnVal)
	{
		#if(defined DEBUG_PRINTF && DL_1)
		Print_DebugMsg(DEBUG_LEVEL1, eReturnVal, "API: \
		BACDEL_Send_You_Are: Destination error \r\n");
		#endif
		return eReturnVal;
	}

	/* Set destination type */
	stServiceArgs.m_stNPDUData.m_eDestinationType = eDestType;
	/* save request-id value */
	stServiceArgs.m_u32RequestID = u32RequestId;

	#ifdef DISPLAY_PARAMETERS
	/* Display parameters */
	Display_Destination_Parameters(u32SrcDevId, u32DestDevId,
		pstDestinationAdd, bDestTypeFlag, eDestType);
	#endif

	/* Copy destination address */
	memcpy(&stServiceArgs.m_stDestBACnetAddr, &stDestAddr, sizeof(BACnetAddress_t));

	/* check destination type flag */
	if(true == bDestTypeFlag)
	{
		/* save device Id */
		stServiceArgs.m_u32DeviceID = u32DestDevId;
	}

	/* Assign all parameters required to send YOU-ARE */
	memcpy(&stServiceArgs.m_stNPDUData.m_stAPDUData.m_stServiceChoice.m_stYOU_ARE_Request,
		pstYouAreData, sizeof(dda_you_are_t));

	/* Generate the request */
	stInitRet = BACDEL_Generate_Aside_Request(pVirtualDev->m_u8DvSADR, &stServiceArgs, NULL);
	/* validate the return value */
	if(BACDEL_INITIATOR_SUCCESS != stInitRet.m_eRetType)
	{
		/* set the error code */
		eReturnVal = stInitRet.m_eErrorCode;
	}

	/* return token ID */
	*pi32TokenId = stInitRet.m_i32TokenID;

	/* api exit */
	#if(defined DEBUG_PRINTF && DL_3)
	Print_DebugMsg(DEBUG_LEVEL3, BACDEL_EXIT_MESSAGE, "API: \
    BACDEL_Send_You_Are: Exit \r\n");
	#endif

	return eReturnVal;
}
#endif /* BACDEL_SER_DM_DDA_A */
#endif /* BACDEL_PR23 */

